### ISSUE TITLE
Error when adding custom repository in HACS

### ISSUE THREAD

**Issue by phil-the-dev** [gpambrozio/BambuAppDaemon#2]
When I go to add a custom repository in HACS I get the following error. Is there something I did incorrectly?
![image](https://github.com/user-attachments/assets/3ce33a51-1fac-4181-91fe-cf03a599154f)

**Comment by gpambrozio** [comment]
Type should be `AppDaemon`, not `Integration`

**Comment by phil-the-dev** [comment]
AppDaemon is not an option. Is there something else I need to setup to get that as an option? 
![image](https://github.com/user-attachments/assets/7355a3a1-e80c-4be1-95ee-80bbddb5c7b1)

**Comment by phil-the-dev** [comment]
Ohhhh, I didn't realized you had to enable this functionality, I can install it now, thank you!
![image](https://github.com/user-attachments/assets/ab5f8a5c-f827-4b75-9690-5b0e998f0495)
